site_name: pc-gym
site_description: Documentation for pc-gym
site_author: Max Bloor

repo_name: pc-gym
repo_url: https://github.com/MaximilianB2/pc-gym

# navigation
nav: 
  - Home: index.md
  - Environments:
    - First Order System: env/first_order_system.md
    - Continuously Stirred Tank Reactor: env/cstr.md
    # - Second Order System: env/second-order-system.md
    # - Four Tank System: env/4-tank-system.md 
    # - CSTR in Series with Recyle Loop: env/CSTR in Series with Recycle loop.md
    # - Distillation Column: env/distillation-column.md
    - Extraction Column: env/extraction-column.md
    - Nonsmooth Control: env/nonsmooth_control.md
    # - Extraction Column (Reactive): env/extraction-column-react.md
    # - Shell and Tube Heat Exchanger: env/STHE.md
    # - Reactor-Separator-Recycle: env/RSR.md
    # - Biofilm Reactor: env/Biofilm-Reactor.md

  - User Guides:
    - Training: guides/training.md
    - Disturbances: guides/disturbances.md
    - Constraints: guides/constraints.md
    #- Models: guides/models.md
    - Policy Evaluation: guides/Policy Evaluation.md
  - API Reference:
    - Make Environment: API/make_env.md
    - Evaluation Metrics: API/evaluation_metrics.md
    - Integrator: API/integrator.md
    - Models: API/model_classes.md
    - Oracle: API/oracle.md
    - Policy Evaluation: API/policy_evaluation.md

# theme

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme: 
  name: material
  logo: img/pc-gym-blue-no-text.png
  icon:
    repo: fontawesome/brands/github
  language: en
  palette:
    - scheme: default
      primary: custom
      accent: blue-grey
      logo: img/pc-gym-blue-no-text.png
  
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: blue-grey
      logo: img/pc-gym-blue-no-text.png
  
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  favicon: img/pc-gym_icon.png
  features:
    - navigation.tracking # the URL is automatically updated with the active anchor
    - navigation.sections # top-level sections are rendered as groups in the sidebar
    - navigation.tabs # horizontal tabs at the top of the page
    - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight # highlight search result
    - search.share # share button
    - search.suggest # smart suggestion
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - content.code.copy

extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - mkdocstrings
  # - include-markdown
  # - mknotebooks: # enable Jupyter notebooks
  #     enable_default_jupyter_cell_styling: false
  # - mermaid2 # Class diagrams, flowcharts and more
  # - mkdocstrings:
  #     default_handler: python
  #     handlers:
  #       python:
  #         options:
  #           docstring_style: google
  #           merge_init_into_class: yes
  #           show_submodules: no
  #         selection:
  #           inherited_members: false
  #         rendering:
  #           show_source: false
  #           members_order: source
  #           show_if_no_docstring: true
  #           show_signature: true
  #           show_signature_annotations: true
  #           show_root_full_path: false
  #           show_root_heading: true
  #           merge_init_into_class: true
  #           docstring_section_style: spacy